@host = https://localhost
@port = 7254

@Restaurants.API_HostAddress = https://localhost:7254

###

GET {{Restaurants.API_HostAddress}}/api/restaurants

###
GET {{Restaurants.API_HostAddress}}/api/restaurants/7

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "name": "The Golden Spoon 2",
  "description": "Fine dining restaurant with modern European cuisine",
  "category": "Japanese",
  "hasDelivery": true,
  "contactEmail": "contact@goldenspoon.com",
  "contactNumber": "997-555-0123",
  "street": "123 Main Street",
  "city": "New York",
  "postalCode": "10001"
}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/7

###

Patch {{Restaurants.API_HostAddress}}/api/restaurants/5
Content-Type: application/json

{
  "name": "The Golden Spoon 2",
  "description": "Fine dining restaurant with modern European cuisine"
}

###
@restaurantId=17
POST {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes
Content-Type: application/json

  {
    "name": "Truffle Mushroom Risotto",
    "description": "Creamy Arborio rice with wild mushrooms, parmesan, and a touch of black truffle oil.",
    "price": 22.50,
    "kiloCalorities": 780
  }

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/7/dishes/9

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/7/dishes

###
