@host = https://localhost
@port = 7254
@Restaurants.API_HostAddress = https://localhost:7254
@token = CfDJ8JY-0T_h_shGpkwETFYpi1sAWSdsa9HrzXSywYcplQGSP0r3NHG4PPAfPvOPTvlNWvd9Fjn_aoli0ImLaxKWCYHRM5DziazDloiNHXTj1-_o9cirNCanr89ze8up4KYIvFe4RP4_TbbWs5DJNov73xoswYq654SSKEv-epQeLVsT1j66zW7Fb37vGpaI2DUelhxxmO0sYawKXt-38CfZhfajMx_D3MiTLXqLnEPotnbiQHAJuvwvQWbjRumX6oENp0Zod_v9sBG6v40GTKs4qE9JJBcUscY0yki5tchNZvGkkvyTNBwS4DmZMwxvOJ_fj4KaUy9aesmO0CtaFUQCeztOyA1QsNQqK0BTV74J7Lq7IvVwZ9NOTHXgxEU8nfs_kAGPVnkqiB_BFsaKJbLrbX_LtHSZKfKcnFdHfvuOIP0ZZpkJnrgnYNOSs_wIkpNAwBUlyj_Qqb8vbaUcE6SwHNpidIYVwg4IALskdrC_Tg1GazKoAEEdzSoL2pvKQ6n_KQZlhxvDhtPLUJxE7tyvvYOHxSIwThg5XzeTD0QXSK0N8EZvJ-yitb1utux7K6Daw_CotlykWNY9fP5XPwsK649UqodpKqCaZhXA0Jjn3xLYUsjMCESOCQbTM_pbSBzp5h5Q0vSZiAsbpRP6FDHUYoq7fhK0fIcy5Hk5gbeuVhqy0C5a3s0W3eeyN1b0lXbCMykB5JVAqrZUj8NZEEBUAA7lIniN2MXbTot9-BYJ77KAs79quXJQK5EVjauldlE_ZEjHJBF18bhFVnUySpTG6VCqVCUVIBycEYPXGcmib_8OcW1RnsrJkKSq0P3_D6wG966n4lRyxnIwnHA-ERbZPw4s_pjUYntGJRnXxzTZwe6DxNETKzP0atCLS9f6PkcxTA

###

GET {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}

###
GET {{Restaurants.API_HostAddress}}/api/restaurants/6
Authorization: Bearer {{token}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Owner Restaurant",
  "description": "A typical US diner",
  "category": "American",
  "hasDelivery": true,
  "contactEmail": "contact@dinerA.com",
  "contactNumber": "991-515-3333",
  "street": "18 Main Street",
  "city": "New York",
  "postalCode": "10033"
}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/7

###

Patch {{Restaurants.API_HostAddress}}/api/restaurants/5
Content-Type: application/json

{
  "name": "The Golden Spoon 2",
  "description": "Fine dining restaurant with modern European cuisine"
}

###
@restaurantId=10
POST {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes
Content-Type: application/json

  {
    "name": "Truffle Mushroom Risotto",
    "description": "Creamy Arborio rice with wild mushrooms, parmesan, and a touch of black truffle oil.",
    "price": 22.50,
    "kiloCalorities": 780
  }

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/6/dishes/8
Authorization: Bearer {{token}}
###

GET {{Restaurants.API_HostAddress}}/api/restaurants/6/dishes
Authorization: Bearer {{token}}
###
###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/10/dishes

###
POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json
{
  "userName": "user123",
  "email": "user123@example.com",
  "password": "Abc123!!!",
  "emailConfirmed": false,
  "phoneNumber": "+1-000-000-0000",
  "twoFactorEnabled": false,
  "lockoutEnabled": true
}

###
POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json
{
  "email": "user123@example.com",
  "password": "Abc123!!!"
}

###
PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "nationality": "French",
  "dateOfBirth": "2009-01-01"
}

###
