@host = https://localhost
@port = 7254
@Restaurants.API_HostAddress = https://localhost:7254
@token = CfDJ8JY-0T_h_shGpkwETFYpi1t4VO-sPEOD5BBmjnTcPuM1NzkIa3eq2b8ScCZcg3xj9NMnjMpU5wXTiA_3E7WmfGviNj3AWbleGYw8Rl8cctyrCshKr01GKDr_fXnjwqJNFqJuDnzOgO5XEjcmP6XSqvwcHTgiNb_Y6DoAW9CzjqZ2DYREhtnnA3C4lEKTd5jzjQktZSNQSI8a-IGb0bKsN6AwPbmn9JCCrhD3-PahpqC0-0hWDrZVDLWD6sTb5ik3Hbc3_KgKtgyD3xMhL3rlN-34T0QZqDgpUKQ-TEwJ4NqQTIxLgdIOOpeeLcB5-lfEVn4q2FRL_SesitriNTqLSZYXBttJTiRXT2ReulrVQsJCV3kl300GEsiuGyEt1_fSCp9tFKUCpdrvJy5fFlBHCkGYfmdmCbBfM9BRrBFfGS3rNhRzGw-4F_WdbFM7eRyoLCgo1Oe5uYzBFj_-a9YpUYGwyuY6nm_GViarT8SKIH9DDgpE-umXYv0DWHYZ5QT2vFJI_qkhCFJ52lcVXv1Ppk6nogPkFylL2tg7bFvHvEKX-VScMk6DRKvFtMZf4Ivt-0wDI5Wos0-g_lC-g1BVtSOF0uzOV8DDXZTXmI3xbIDqlh9J7O_flHYtsmWn5PsS9hETY-tO7aOKmx-aOXSqm--7YOFoA3E5waxzudeEWCrhXynXBJ7GymQ8QIsV7kOW0BPC3ipjzbSJl8fCj-NygHU548iCRIw8qJYpeDqvDE7VNEeB5JNXKvOpRzEPEzpf-YsaxSSWJYaibEsjrw2OeqSAMIAo0yhYA87BpVhDE7uh7uI4jSEWkO9zsvHSqJZGKtusSqeFWfNA4iXS_t6p1v8oAbwwXTbJTl_lkl_vINVBsuFeMzs5fknuakOH38Dh3A

###

GET {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}

###
GET {{Restaurants.API_HostAddress}}/api/restaurants/6
Authorization: Bearer {{token}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Italian 2",
  "description": "Fine dining restaurant with modern European cuisine",
  "category": "Italian",
  "hasDelivery": true,
  "contactEmail": "contact@goldenspoon.com",
  "contactNumber": "997-555-0123",
  "street": "123 Main Street",
  "city": "New York",
  "postalCode": "10001"
}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/7

###

Patch {{Restaurants.API_HostAddress}}/api/restaurants/5
Content-Type: application/json

{
  "name": "The Golden Spoon 2",
  "description": "Fine dining restaurant with modern European cuisine"
}

###
@restaurantId=10
POST {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes
Content-Type: application/json

  {
    "name": "Truffle Mushroom Risotto",
    "description": "Creamy Arborio rice with wild mushrooms, parmesan, and a touch of black truffle oil.",
    "price": 22.50,
    "kiloCalorities": 780
  }

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/6/dishes/8
Authorization: Bearer {{token}}
###

GET {{Restaurants.API_HostAddress}}/api/restaurants/6/dishes
Authorization: Bearer {{token}}
###
###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/10/dishes

###
POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json
{
  "userName": "user123",
  "email": "user123@example.com",
  "password": "Abc123!!!",
  "emailConfirmed": false,
  "phoneNumber": "+1-000-000-0000",
  "twoFactorEnabled": false,
  "lockoutEnabled": true
}

###
POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json
{
  "email": "user123@example.com",
  "password": "Abc123!!!"
}

###
PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "nationality": "French",
  "dateOfBirth": "2009-01-01"
}

###
